language: php

php: [5.4, 5.5, 5.6, hhvm]

matrix:
    exclude:
        # Exclude the extra librabbitmq version as HHVM does not use it anyway
        - { php: hhvm, env: LIBRABBITMQ_VERSION=master }

env:
  - LIBRABBITMQ_VERSION=master
  - LIBRABBITMQ_VERSION=v0.5.0

services: [rabbitmq]

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./tests/bin/install_amqp_ext.sh; fi;'
  - composer selfupdate
  - composer install --prefer-source
  - sh -c "sudo ./tests/bin/prepare_rabbit.sh"
